export default function getConfig() {
    return {
        form: {
            required: 'auto',
            labelAlign: 'right',
            inputAlign: 'right',
            labelColor: '#9ca3af',
            labelBold: false,
            valueColor: '#111827',
            valueBold: false,
        },
        row: {
            show: true,
            gutter: 0,
        },
        submitBtn: {
            type: 'primary',
            loading: false,
            disabled: false,
            block: true,
            innerText: '',
            size: 'small',
            show: true,
            col: undefined,
            click: undefined,
        },
        resetBtn: {
            type: 'default',
            loading: false,
            disabled: false,
            block: true,
            innerText: '',
            size: 'small',
            show: false,
            col: undefined,
            click: undefined,
        },
        detailBtn: {
            type: 'primary',
            loading: false,
            disabled: false,
            block: true,
            innerText: '',
            size: 'small',
            show: false,
            col: undefined,
            click: undefined,
            routeName: '',
        },
    };
}
